# Generated by Django 5.1.1 on 2024-10-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=255)),
                ('produit', models.CharField(max_length=255)),
                ('commentaire', models.TextField()),
                ('note', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
