# Generated by Django 5.1.1 on 2024-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
