# Generated by Django 5.1.1 on 2024-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_blogpost_content_en_blogpost_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
