# Generated by Django 5.1.1 on 2024-10-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_blogpost_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
