# Generated by Django 5.1.1 on 2024-10-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_produit_reponse'),
        ('users', '0015_alter_blogpost_author'),
    ]

    operations = [
    ]
